# Configure this Discovery Server
eureka:
  instance:
    virtual-host-name: 172.17.0.2
    hostname: 172.17.0.2
    #enableSelfPreservation: false
    preferIpAddress: true
    # DO NOT DO THIS IN PRODUCTION
    leaseRenewalIntervalInSeconds: 5

  client:
    registerWithEureka: false
    fetchRegistry: false
    #register-with-eureka: false
    #fetch-registry: false

server:
  port: 1111

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

