# Spring properties
spring:
  application:
     name: @application.name@  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    enabled: true
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
                             # Template location for this application only

# Map the error path to error template (for Thymeleaf)
error:
  path: /error

# HTTP Server
server:
  port: @eureka.port@   # HTTP (Tomcat) port

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
eureka:

  client:
    serviceUrl:
      defaultZone: http://@eureka.server@/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    virtual-host-name: @virtual-hostname@
    metadata-map:
      port: @akka.port@
  # what is my application virtual ip address? (clients can query on this vipAddress)
 # vipAddress: akka.idtrust.com.br
 # name: akka
management:
    security:
      enabled: false
